# Generated by Django 5.1.4 on 2025-01-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('company_name', models.TextField()),
                ('emails', models.TextField()),
                ('phones', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
    ]
