# Generated by Django 5.1.4 on 2025-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintable',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
